-- Migration 0008: Phase 2 Batch C Tables (Internal Linker, PageSpeed, Local SEO, Content Refresher)
-- Created: 2024

-- =====================================================
-- Internal Linker Tables
-- =====================================================

-- Store internal links discovered by crawler
CREATE TABLE IF NOT EXISTS internal_links (
  link_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  
  from_url TEXT NOT NULL,
  to_url TEXT NOT NULL,
  anchor_text TEXT,
  context TEXT, -- Surrounding text
  is_nofollow BOOLEAN DEFAULT false,
  page_depth INTEGER, -- Depth from homepage
  
  discovered_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(project_id, from_url, to_url, anchor_text)
);

CREATE INDEX idx_internal_links_project_from ON internal_links(project_id, from_url);
CREATE INDEX idx_internal_links_project_to ON internal_links(project_id, to_url);
CREATE INDEX idx_internal_links_discovered_at ON internal_links(discovered_at DESC);

-- Store link suggestions generated by agent
CREATE TABLE IF NOT EXISTS link_suggestions (
  suggestion_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  
  from_url TEXT NOT NULL,
  to_url TEXT NOT NULL,
  relevance_score DECIMAL(3,2) CHECK (relevance_score >= 0 AND relevance_score <= 1),
  priority TEXT CHECK (priority IN ('high', 'medium', 'low')),
  reason TEXT,
  suggested_anchor_texts TEXT[], -- Array of suggested anchor text options
  expected_benefits TEXT[], -- Array of expected benefits
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'implemented', 'rejected')),
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  implemented_at TIMESTAMPTZ
);

CREATE INDEX idx_link_suggestions_project_priority ON link_suggestions(project_id, priority, status);
CREATE INDEX idx_link_suggestions_status ON link_suggestions(status);

-- =====================================================
-- PageSpeed Agent Tables
-- =====================================================

-- Store PageSpeed Insights audit results
CREATE TABLE IF NOT EXISTS pagespeed_audits (
  audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  
  url TEXT NOT NULL,
  device TEXT CHECK (device IN ('mobile', 'desktop')),
  
  -- Lighthouse scores (0-100)
  lighthouse_scores JSONB, -- {performance, accessibility, bestPractices, seo, pwa}
  
  -- Core Web Vitals (milliseconds and scores)
  lab_core_web_vitals JSONB, -- {lcp, fid, cls, fcp, ttfb, tbt}
  field_core_web_vitals JSONB, -- Real user data from CrUX
  
  -- Loading experience
  loading_experience TEXT CHECK (loading_experience IN ('FAST', 'AVERAGE', 'SLOW')),
  
  -- Optimization opportunities
  opportunities JSONB, -- Array of optimization suggestions
  diagnostics JSONB, -- Array of diagnostic info
  
  audited_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_pagespeed_audits_project_url ON pagespeed_audits(project_id, url);
CREATE INDEX idx_pagespeed_audits_device ON pagespeed_audits(device);
CREATE INDEX idx_pagespeed_audits_audited_at ON pagespeed_audits(audited_at DESC);

-- Store Core Web Vitals time series for trending
CREATE TABLE IF NOT EXISTS cwv_timeseries (
  timeseries_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  
  url TEXT NOT NULL,
  device TEXT CHECK (device IN ('mobile', 'desktop')),
  
  -- Core Web Vitals metrics
  lcp DECIMAL(10,2), -- Largest Contentful Paint (ms)
  fid DECIMAL(10,2), -- First Input Delay (ms)
  cls DECIMAL(5,3), -- Cumulative Layout Shift (score)
  fcp DECIMAL(10,2), -- First Contentful Paint (ms)
  ttfb DECIMAL(10,2), -- Time to First Byte (ms)
  tbt DECIMAL(10,2), -- Total Blocking Time (ms)
  
  -- Lighthouse performance score
  performance_score INTEGER CHECK (performance_score >= 0 AND performance_score <= 100),
  
  measured_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_cwv_timeseries_project_url_time ON cwv_timeseries(project_id, url, measured_at DESC);
CREATE INDEX idx_cwv_timeseries_measured_at ON cwv_timeseries(measured_at DESC);

-- Convert to TimescaleDB hypertable for efficient time-series queries
-- SELECT create_hypertable('cwv_timeseries', 'measured_at', if_not_exists => TRUE);

-- =====================================================
-- Local SEO Agent Tables
-- =====================================================

-- Store Google My Business profiles
CREATE TABLE IF NOT EXISTS local_business_profiles (
  profile_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  
  gmb_profile_id TEXT, -- External GMB ID
  business_name TEXT NOT NULL,
  address JSONB, -- {street, city, state, zip, country}
  phone TEXT,
  website TEXT,
  category TEXT,
  
  rating DECIMAL(2,1) CHECK (rating >= 0 AND rating <= 5),
  review_count INTEGER DEFAULT 0,
  
  -- Additional details
  hours JSONB, -- {monday: "9:00 AM - 5:00 PM", ...}
  attributes TEXT[], -- Array of business attributes
  photos_count INTEGER DEFAULT 0,
  posts_count INTEGER DEFAULT 0,
  
  -- Status
  is_verified BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT true,
  
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_local_business_profiles_project ON local_business_profiles(project_id);
CREATE INDEX idx_local_business_profiles_gmb_id ON local_business_profiles(gmb_profile_id);

-- Store GMB reviews
CREATE TABLE IF NOT EXISTS gmb_reviews (
  review_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES local_business_profiles(profile_id) ON DELETE CASCADE,
  
  external_review_id TEXT, -- External review ID from GMB
  author TEXT,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  review_text TEXT,
  sentiment TEXT CHECK (sentiment IN ('positive', 'neutral', 'negative')),
  
  reply_text TEXT,
  replied_at TIMESTAMPTZ,
  
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(profile_id, external_review_id)
);

CREATE INDEX idx_gmb_reviews_profile ON gmb_reviews(profile_id, published_at DESC);
CREATE INDEX idx_gmb_reviews_rating ON gmb_reviews(rating);
CREATE INDEX idx_gmb_reviews_sentiment ON gmb_reviews(sentiment);
CREATE INDEX idx_gmb_reviews_replied ON gmb_reviews(replied_at);

-- Store NAP citations across the web
CREATE TABLE IF NOT EXISTS citation_records (
  citation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES local_business_profiles(profile_id) ON DELETE CASCADE,
  
  source TEXT NOT NULL, -- Yelp, Yellow Pages, Facebook, etc.
  source_url TEXT,
  domain_authority INTEGER,
  
  -- NAP data found on source
  name TEXT,
  address TEXT,
  phone TEXT,
  
  -- Consistency check
  is_consistent BOOLEAN DEFAULT true,
  inconsistencies TEXT[], -- ['name', 'address', 'phone']
  
  last_checked_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(profile_id, source)
);

CREATE INDEX idx_citation_records_profile ON citation_records(profile_id);
CREATE INDEX idx_citation_records_consistent ON citation_records(is_consistent);
CREATE INDEX idx_citation_records_checked_at ON citation_records(last_checked_at DESC);

-- Store local ranking data
CREATE TABLE IF NOT EXISTS local_rankings (
  ranking_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES local_business_profiles(profile_id) ON DELETE CASCADE,
  
  keyword TEXT NOT NULL,
  location TEXT NOT NULL,
  
  position INTEGER,
  map_pack_position INTEGER, -- Position in Google Map Pack (1-3)
  organic_position INTEGER, -- Position in organic results
  
  tracked_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_local_rankings_profile_keyword ON local_rankings(profile_id, keyword, tracked_at DESC);
CREATE INDEX idx_local_rankings_tracked_at ON local_rankings(tracked_at DESC);

-- =====================================================
-- Content Refresher Agent Tables
-- =====================================================

-- Store content freshness checks
CREATE TABLE IF NOT EXISTS content_freshness_checks (
  check_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  
  url TEXT NOT NULL,
  title TEXT,
  last_updated DATE,
  days_since_update INTEGER,
  word_count INTEGER,
  
  -- Ranking data
  current_rankings JSONB, -- {keyword: position}
  historical_rankings JSONB, -- {keyword: position}
  ranking_trend TEXT CHECK (ranking_trend IN ('up', 'down', 'stable')),
  avg_ranking_change DECIMAL(5,1),
  
  -- Traffic data
  current_traffic INTEGER,
  historical_traffic INTEGER,
  traffic_trend TEXT CHECK (traffic_trend IN ('up', 'down', 'stable')),
  traffic_change_percent INTEGER,
  
  -- Freshness assessment
  is_fresh BOOLEAN,
  stale_days INTEGER,
  refresh_priority TEXT CHECK (refresh_priority IN ('high', 'medium', 'low')),
  refresh_reason TEXT,
  
  checked_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_content_freshness_project_priority ON content_freshness_checks(project_id, refresh_priority);
CREATE INDEX idx_content_freshness_checked_at ON content_freshness_checks(checked_at DESC);
CREATE INDEX idx_content_freshness_url ON content_freshness_checks(project_id, url);

-- Store update recommendations
CREATE TABLE IF NOT EXISTS content_update_recommendations (
  recommendation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  check_id UUID NOT NULL REFERENCES content_freshness_checks(check_id) ON DELETE CASCADE,
  
  url TEXT NOT NULL,
  recommendation_type TEXT CHECK (recommendation_type IN ('statistics', 'images', 'links', 'sections', 'keywords', 'comprehensive')),
  priority TEXT CHECK (priority IN ('high', 'medium', 'low')),
  reason TEXT,
  suggestions TEXT[], -- Array of specific suggestions
  estimated_impact TEXT,
  
  -- Competitor insights (optional)
  competitor_insights JSONB, -- {competitorUrl, missingTopics[], wordCountDiff}
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'rejected')),
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX idx_content_update_recs_check ON content_update_recommendations(check_id);
CREATE INDEX idx_content_update_recs_priority ON content_update_recommendations(priority, status);
CREATE INDEX idx_content_update_recs_status ON content_update_recommendations(status);

-- =====================================================
-- Row Level Security (RLS)
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE internal_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE link_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagespeed_audits ENABLE ROW LEVEL SECURITY;
ALTER TABLE cwv_timeseries ENABLE ROW LEVEL SECURITY;
ALTER TABLE local_business_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE gmb_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE citation_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE local_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_freshness_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_update_recommendations ENABLE ROW LEVEL SECURITY;

-- Create RLS policies (tenant isolation via project_id)
CREATE POLICY tenant_isolation_internal_links ON internal_links
  USING (project_id IN (SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid));

CREATE POLICY tenant_isolation_link_suggestions ON link_suggestions
  USING (project_id IN (SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid));

CREATE POLICY tenant_isolation_pagespeed_audits ON pagespeed_audits
  USING (project_id IN (SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid));

CREATE POLICY tenant_isolation_cwv_timeseries ON cwv_timeseries
  USING (project_id IN (SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid));

CREATE POLICY tenant_isolation_local_business_profiles ON local_business_profiles
  USING (project_id IN (SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid));

CREATE POLICY tenant_isolation_gmb_reviews ON gmb_reviews
  USING (profile_id IN (SELECT profile_id FROM local_business_profiles WHERE project_id IN (
    SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid
  )));

CREATE POLICY tenant_isolation_citation_records ON citation_records
  USING (profile_id IN (SELECT profile_id FROM local_business_profiles WHERE project_id IN (
    SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid
  )));

CREATE POLICY tenant_isolation_local_rankings ON local_rankings
  USING (profile_id IN (SELECT profile_id FROM local_business_profiles WHERE project_id IN (
    SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid
  )));

CREATE POLICY tenant_isolation_content_freshness_checks ON content_freshness_checks
  USING (project_id IN (SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid));

CREATE POLICY tenant_isolation_content_update_recommendations ON content_update_recommendations
  USING (check_id IN (SELECT check_id FROM content_freshness_checks WHERE project_id IN (
    SELECT id FROM projects WHERE tenant_id = current_setting('app.current_tenant_id', true)::uuid
  )));

-- =====================================================
-- Triggers for updated_at timestamps
-- =====================================================

CREATE TRIGGER update_internal_links_updated_at BEFORE UPDATE ON internal_links
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_link_suggestions_updated_at BEFORE UPDATE ON link_suggestions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_local_business_profiles_updated_at BEFORE UPDATE ON local_business_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_gmb_reviews_updated_at BEFORE UPDATE ON gmb_reviews
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_citation_records_updated_at BEFORE UPDATE ON citation_records
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_content_update_recommendations_updated_at BEFORE UPDATE ON content_update_recommendations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
